name: Update All Branches from Main

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-branches:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push updates

    steps:
      - name: Set Git Identity (Fix Empty Ident Error)
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions@github.com"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all branches

      - name: Ensure logs directory exists
        run: mkdir -p logs

      - name: Append new log entry to log file
        run: |
          TIMESTAMP=$(date)
          echo "" >> logs/branch_update_log.txt
          echo "--- [$TIMESTAMP] - Sync Fork with Upstream ---" >> logs/branch_update_log.txt
          echo "" >> logs/branch_update_log.txt

      - name: Get all branches except main
        id: branches
        run: |
          echo "BRANCHES=$(git branch -r | grep -v main | awk -F'origin/' '{print $2}' | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Merge main into other branches
        run: |
          for branch in $BRANCHES; do
            git checkout $branch
            if git merge origin/main --no-edit; then
              echo "- ✅ Merged into \`$branch\`" >> logs/branch_update_log.txt
              git push origin $branch
            else
              echo "- ❌ Conflict detected in \`$branch\`, skipping..." >> logs/branch_update_log.txt
              git merge --abort
            fi
          done

      - name: Ensure Git Tracks Log File (Fix .gitignore Issues)
        run: |
          git rm -r --cached logs/branch_update_log.txt || true
          git add -f logs/branch_update_log.txt

      - name: Commit log files (Fix Silent Push Errors)
        run: |
          git commit -m "Update branch update logs" || echo "No new changes to commit"

      - name: Force Push Changes to Main (Fix Branch Issues)
        run: |
          git push origin HEAD:main --force || echo "No log updates to push"
